#!/bin/sh

cd `dirname $(readlink -f $0)`

case $1 in
	kieran|kbingham)
		echo "Welcome Admin"
		;;
	*)
		echo "Unregistered user"
		;;
esac

case $SSH_ORIGINAL_COMMAND in
	upgrade)
		git fetch origin
		git reset --hard origin/master
		./update-ssh-keys
		;;
	*)
		echo "Unknown command $SSH_ORIGINAL_COMMAND"
		;;
esac

