#!/bin/bash

cd `dirname $(readlink -f $0)`

BOARDS="salvator-x salvator-xs"

if [[ $SSH_ORIGINAL_COMMAND =~ .*LAB_DEBUG=1.* ]]
then
	echo SSH_ORIGINAL_COMMAND : $SSH_ORIGINAL_COMMAND
	echo [$0] $*
	set -x
fi

case $1 in
	kieran|kbingham)
		ADMIN=true
		;;
	*)
		echo "Unregistered user"
		;;
esac

case $SSH_ORIGINAL_COMMAND in
	shell*)
		if [ -z ${ADMIN+x} ];
		then
			echo "You are not an admin";
			exit;
		else
			echo "Welcome Admin"
			bash;
		fi;
		;;
	ls*)
		for b in $BOARDS; do echo $b; done;
		;;
	upgrade*)
		git fetch origin
		git reset --hard origin/master
		./update-ssh-keys
		;;
	serial*)
		echo "./$SSH_ORIGINAL_COMMAND"
		./$SSH_ORIGINAL_COMMAND
		;;
	help*)
		echo "Use the force, Luke ..."
		;;
	*)
		echo "Unknown command: $SSH_ORIGINAL_COMMAND"
		;;
esac

