#!/bin/sh

cd `dirname $(readlink -f $0)`

case $1 in
	kbingham)
		echo "Welcome Admin"
		;;
esac

case $2 in
	upgrade)
		git fetch origin
		git reset --hard origin/master
		;;
	*)
		echo "Unknown command $1"
		;;
esac

